//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Badgibot
{
    using System;
    
    public enum MessageType : long
    {
        Text = 0,
        Image = 1,
        Audio = 2,
        Video = 3
    }
}
