//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Badgibot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessagesId { get; set; }
        public string Author { get; set; }
        public System.DateTime SentAt { get; set; }
        public MessageType Type { get; set; }
        public string Content { get; set; }
    }
}
